services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8081"
    networks: [ appnet ]
  app:
    build: ./app
    environment:
      - OIDC_ISSUER=http://keycloak:8081/realms/health
      - OIDC_AUDIENCE=health-api
      - APP_DATA_KEY=/run/secrets/data_key
    secrets:
      - data_key
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/app/certs   # Mount local certs folder into container
    depends_on: [ keycloak ]
    networks: [ appnet ]
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mount Docker socket so Jenkins can use host Docker
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks: [ appnet ]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks: [ appnet ]
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: [ appnet ]
  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/config.yml
    ports:
      - "3100:3100"
    networks: [ appnet ]
  promtail:
    image: grafana/promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks: [ appnet ]
secrets:
  data_key:
    file: ./keys/data.key
volumes:
  jenkins_home:
networks:
  appnet: